version: '3.4'

services:
  postgres:
    container_name: threadsapp
    image: postgres
    ports:
      - "5432:5432"  # Added double quotes around the port mapping
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:  # Corrected the spelling of "environment"
      POSTGRES_USER: postgres
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: threads

volumes:
  postgres_data:
